ヘッダーとメインビジュアル追加
shiori-yasutani/bokurahatensai pull request #2
Opened 2018-09-04 15:36 UTC by shiori-yasutani

ナビゲーションのリストと、メインビジュアルを作成しました。
メインビジュアル：テキスト「こだわりを育てよう」が思った位置に来ませんでした。

2018-09-04 23:24 UTC, masatakashida commented
>メインビジュアル：テキスト「こだわりを育てよう」が思った位置に来ませんでした。

思った位置というのがわかるものを添付お願いします！

2018-09-05 11:38 UTC, masatakashida requested changes
ページいい感じで感動しました！
修正がんばってみてください！

2018-09-05 11:38 UTC, masatakashida commented on README.md
> +
READMEがコンフリクトおきているので、ここの３、４行目消してもう一度コミットしましょう！

2018-09-05 11:38 UTC, masatakashida commented on index.html
> +              <li><a href="">トップページ<br><span class="english">top page</span></a></li>
englishのところ小さい文字にした方が読みやすいかもね！

2018-09-05 11:38 UTC, masatakashida commented on stylesheet.css
> +  -webkit-box-pack: space-evenly;
細かいけど、揃えよう

2018-09-17 06:10 UTC, masatakashida commented
このPRの状況どうでしょうか？

2018-09-17 06:17 UTC, masatakashida commented
わからないことでてきたら、すぐにここで聞いてください！

2018-12-22 02:33 UTC, shiori-yasutani commented
## ToDo
- [ ] コンフリクト解消
- [ ] english文字サイズ小さくする
- [ ] 文字位置揃える

2018-12-22 02:38 UTC, shiori-yasutani commented
Githubについて調べる

2018-12-22 03:54 UTC, merged